# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install specific versions of Flask, Flask-CORS, MarkupSafe, and Jinja2
RUN pip install --no-cache-dir Flask==1.1.4 Flask-CORS==3.0.10 MarkupSafe==1.1.1 Jinja2==2.11.3 Werkzeug==0.16.1

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]
